Complementary change for #213 (#240)
* Fix auto extend error when using an ActiveJob wrapper

ActiveJob::QueueAdapters::ShoryukenAdapter::JobWrapper
Could not auto extend the message ActiveJob::QueueAdapters::ShoryukenAdapter::JobWrapper/<queue_name>/<message> visibility timeout. Error: undefined method `[]' for nil:NilClass

* Fix `Line is too long. [138/120]`

* Fix for `Align the operands of a condition in an "if statement" spanning multiple lines.`

* Fix initialization when the Load Rails option is specified

* Add rspec task

See https://www.relishapp.com/rspec/rspec-core/docs/command-line/rake-task.

* Fix NameError exception in AutoExtendVisibility

When execute command `bundle exec shoryuken -C config/shoryuken.yml --rails`.

> uninitialized constant Shoryuken::Middleware::Server::AutoExtendVisibility::MessageVisibilityExtender::Celluloid (NameError)

* Reduce shutdown wait time

* Run dispatch when processor done or dies

* Daemonize before loading environment

Daemonizing forks the process, which kills all other running threads. If
your Rails app starts threads during initialization, they will currently
be killed almost immediately.

* Document producer setup (https://github.com/phstc/shoryuken/issues/188)

* Add release date back on the change log

* Bump version to 2.0.7

* Add new author

* Load Celluloid before environment

* Bump version to 2.0.8

* Fix error when initialize shoryuken daemonize

* Fix daemonization broken in #219

* Bump version to 2.0.9

* Revert "Run dispatch when processor done or dies" (#226)

This reverts commit f4640d97950c1783a061195855d93994725ed64a.

* Bump version to 2.0.10

* I'm a completely stupid and removed the wrong version in rubygems

* Update CHANGELOG to add 2.0.11

* Minor sample default_worker cleanup

* Complementary fix for #213. Pass body to worker_name for calls from AutoExtendVisibility